Create README.md
dataiku/dataiku-contrib pull request #277
Opened 2022-02-04 22:06 UTC by gbetegon88

2022-02-08 17:17 UTC, JaneBellaiche requested changes
Just suggested a few changes on the text. Also, have you check with the macro the behavior of the different cases we quote on the "dependencies" section? Let's ensure this is all true before merging

2022-02-08 17:17 UTC, JaneBellaiche commented on clear-intermediate-datasets/README.md
> +
I would add a brief description of the macro ( just 1- 2 lines)

2022-02-08 17:17 UTC, JaneBellaiche commented on clear-intermediate-datasets/README.md
> +Partitioned and Shared datasts are paticularly sensitive, and specific options has been added to remove
```suggestion
###Partitioned and shared datasets
Partitioned and shared datasets are particularly sensitive. You can select the available options to keep your partitioned and shared datasets in the flow. 
```

2022-02-08 17:17 UTC, JaneBellaiche commented on clear-intermediate-datasets/README.md
> +- It's explicitily linked to an scenario step
It is preferred to use a neutral ton than imperative verbs, for e.g 
```suggestion
### Dependencies
Any of the following datas associated to a dataset can be affected when clearing it:
- Charts will be cleared
- Insights published in a dashboard will be cleared
- Insights shared in a workspace will be cleared
-  Scenario with the dataset as input of a scenario step will break 
```

2022-02-08 19:41 UTC, gbetegon88 commented
> Just suggested a few changes on the text. Also, have you check with the macro the behavior of the different cases we quote on the "dependencies" section? Let's ensure this is all true before merging

Thanks for your comments @JaneBellaiche. I'm planning to go over these either Thursday or Friday.

2022-02-17 18:17 UTC, gbetegon88 commented
@JaneBellaiche I readded the README.md. I think all comments should be covered now in commit: [c413a3281a5dc546ca2c426a0726efd8f26e50c3](https://github.com/gbetegon88/dataiku-contrib/commit/c413a3281a5dc546ca2c426a0726efd8f26e50c3)

2022-05-18 13:03 UTC, JaneBellaiche commented on clear-intermediate-datasets/README.md
> +## CAUTION!
I'd remove the scary "!" 😃

2022-06-30 10:47 UTC, JaneBellaiche requested changes
Just a last typo and then you can merge this PR :)

2022-06-30 10:47 UTC, JaneBellaiche commented on clear-intermediate-datasets/README.md
> +Partitioned and shared datasets are particularly sensitive. Selecting the available options _Keep partitioned datasets_ and _Keep shared datasets_ will ensured that they are not cleared.
```suggestion
Partitioned and shared datasets are particularly sensitive. Selecting the available options _Keep partitioned datasets_ and _Keep shared datasets_ will ensure that they are not cleared. 
```

2022-06-30 14:29 UTC, merged